### ISSUE TITLE
Reliability bug?

### ISSUE THREAD

**Issue by neb5555** [Angel-125/BARIS#1]
Hi Angel
love the mod it is great.

Is this a bug please let me know if I am doing something wrong?

Just having an issue with the reliability of the ship not being updated to the true value. I am using default settings and I made 7 tests of this vehicle but on launch it still would not increase the reliability. But as you can see in the VAB it is showing the increased reliability under the test branch feature shows the correct value of 27. Where as launch shows 25.

If you need anything further from me let me know. I am using many mods including KCT.

![pic1](https://user-images.githubusercontent.com/31667160/30075297-7c8df9c8-926c-11e7-947b-7a315f4214fd.jpg)
![pic2](https://user-images.githubusercontent.com/31667160/30075300-7e3bc110-926c-11e7-808f-3c69ccf83926.jpg)

**Comment by Angel-125** [comment]
Can you help me walk through the steps you took? It sounds like you created the vessel, started building it in KCT, then used the Test Bench. Is that correct?

Also, do you have a link to KCT working in KSP 1.3?

**Comment by neb5555** [comment]
Link for KCT download below, I have currently installed build number 34 under the Kerbal Construction Time Beta section. Have not tried updating to most recent build but my current one works fine with KSP 1.3.

http://magico13.net:8080/

Steps were as follows:

Built the rocket as above and built it using KCT and built the same rocket and launched it 7 times in a row. Only building one at a time launching then building the next.

When launched on the rocket pad I did a static test each time with some failures and some engines/tanks working fine.

The reliability figure never increased in the new launches for the individual rocket parts or for the vessel as a whole. BUT under the part testing bench the Pre-Simulation Reliability figure you can see the cap is at 27 so has increased from 25!!! So its like the reliability is increasing but not being included on the new vessel. Considering it has 5 engines x 7 vessels the reliability should improve a tiny bit even with bad RND.

I did not use the part testing benching to improve reliability but just the 7 static test launches.

**Comment by Angel-125** [comment]
Ok, I think it has to do with how KCT works. I think KCT takes a snapshot of the vessel as it was when you started building it, and that might affect things. I'm to too familiar with KCT, do you have to build the craft each time you launch it? It might be using a stale version of the craft.

**Comment by neb5555** [comment]
Okay it looks like your thoughts are correct. Just loaded up KSP and loaded the same save and created a new vessel and the fuel tanks and engines are showing the correct reliability. See Pic. 

So when I create a new vehicle is uses the correct values of reliability. But loading a vessel is giving the stale version of the vessel. I just tried loading the old craft with the same result.

And the answer to your question regarding KCT is yes you have to build each vessel seperately through the VAB/SPH unless you decide to copy one that is already in progress (I always built them through the VAB)

![pic3](https://user-images.githubusercontent.com/31667160/30083615-1bb5a4d2-9287-11e7-830e-7ae9f3b13209.jpg)

**Comment by Angel-125** [comment]
[See if 1.3.8 fixes it](https://github.com/Angel-125/BARIS/releases/tag/v1.3.8), I made some changes for KCT.

**Comment by Angel-125** [comment]
Should be fixed in latest pre-release.
