### ISSUE TITLE
Change mantinace resource to CRP machinery, to intigrate bettwer with MKS.

### ISSUE THREAD

**Issue by TheToric** [Angel-125/BARIS#4]
if MKS is installed, you can then remove the ore to mantinace conversion, forcing use of MKS conversion changes.
I would do this a PR, but I don't have a dev environment for plugin tweaks.

**Comment by Angel-125** [comment]
I don't use MKS, so somebody skilled with it will need to make a MM patch. Thanks for the suggestion though. :)

**Comment by TheToric** [comment]
I would be happy to do it, but some hardcoded values in the plugin need to be changed. I was more thinking, that, unless you use equipment in your other mods, it may be best to use a CRP resource instead of defining your own. unfortunatly, sutch an update would probably be save breaking...
