### ISSUE TITLE
ModuleManager issues

### ISSUE THREAD

**Issue by blowfishpro** [Angel-125/BARIS#6]
`WildBlueIndustries/000BARIS/ModuleManagerPatches/MM_BARIS.cfg` has a few patches marked `:FOR[BARIS]:FINAL`

`:FOR[mod]` and `:FINAL` are conflicting.  This is currently a silent failure in ModuleManager, but will become a loud error in the next version (error printed in the loading screen, no cache generated)

**Comment by Angel-125** [comment]
Fixed in BARIS 1.4.8
