### ISSUE TITLE
Not on CKAN

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [Angel-125/BARIS#7]
Pls <3

**Comment by Angel-125** [comment]
pay me $50000 usd up front and I will. :)

**Comment by SIGSTACKFAULT** [comment]
Give me... ~~One~~ Two good reasons

**Comment by Angel-125** [comment]
1. No
2. No
3. If I find any of my mods on CKAN without my consent I will sue. I've made my position very clear to the stakeholders and I don't have to explain myself to you.
